using System.Numerics;
using Content.Shared.Photography;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Photography.UI;

[GenerateTypedNameReferences]
public sealed partial class PhotoWindow : BaseWindow
{
    public PhotoWindow()
    {
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += _ => Close();
    }

    public void SetVisuals(PhotoComponent photo)
    {
    }

    // Drag by grabbing anywhere
    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
