// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.Pinpointer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Pinpointer.UI;

[GenerateTypedNameReferences]
public sealed partial class PinpointerUplinkMenu : FancyWindow
{
    public FancyWindow? DnaWindow;

    public HashSet<TrackedItem> ItemListSet = [];

    public Action<NetEntity>? OnTargetPicked;
    public Action<string>? OnDnaPicked;

    private string _searchText = string.Empty;

    public PinpointerUplinkMenu()
    {
        RobustXamlLoader.Load(this);
        SearchBar.OnTextChanged += OnSearchChanged;
        DNASearch.OnPressed += OnDNASearch;
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text.Trim().ToLower();
        PopulateList();
    }

    private void OnDNASearch(BaseButton.ButtonEventArgs args)
    {
        if (DnaWindow != null)
        {
            DnaWindow.Open();
            return;
        }

        DnaWindow = new FancyWindow
        {
            Title = Loc.GetString("pinpointer-ui-uplink-search-by-dna"),
            SetSize = new Vector2(200, 200),
        };


        var boxContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };

        var lineEdit = new LineEdit
        {
            PlaceHolder = Loc.GetString("pinpointer-ui-uplink-enter-dna"),
            SetSize = new Vector2(150, 30),
        };

        var button = new Button()
        {
            Text = Loc.GetString("pinpointer-ui-uplink-accept"),
            Modulate = Color.LimeGreen,
            StyleClasses = { "OpenBoth" },
            SetSize = new Vector2(150, 30),
        };

        button.OnPressed += _ =>
        {
            if (string.IsNullOrEmpty(lineEdit.Text))
                return;

            OnDnaPicked?.Invoke(lineEdit.Text);
        };

        boxContainer.AddChild(lineEdit);
        boxContainer.AddChild(button);
        DnaWindow.AddChild(boxContainer);
        DnaWindow.OpenCentered();
    }

    public void PopulateList()
    {
        ItemList.RemoveAllChildren();

        foreach (var entry in ItemListSet)
        {
            var button = CreateTargetButton(entry.Name, () => OnTargetPicked?.Invoke(entry.Entity));

            if (button == null)
                continue;

            ItemList.AddChild(button);
        }
    }

    private Button? CreateTargetButton(string fullName, Action onClick)
    {
        if (!fullName.Contains(_searchText, StringComparison.CurrentCultureIgnoreCase))
            return null;

        var button = new Button
        {
            ToolTip = fullName,
            StyleClasses = { "OpenBoth" },
            SetHeight = 30,
            Margin = new Thickness(5, 0, 5, 5),
            HorizontalExpand = true,
        };

        var label = new Label
        {
            Text = fullName,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
        };

        button.OnPressed += _ => onClick();
        button.AddChild(label);

        return button;
    }
}

