- type: entity
  id: BaseStation
  abstract: true
  components:
    - type: StationData
    - type: StationMinimap #SS220 Camera-Map
      minimapData: !type:StationMinimapData
        mapScale: 5

- type: entity
  id: BaseStationCargo
  abstract: true
  components:
    - type: StationBankAccount
    - type: StationCargoOrderDatabase
    - type: StationCargoBountyDatabase

- type: entity
  id: BaseStationJobsSpawning
  abstract: true
  components:
    - type: StationJobs
      availableJobs: {}
    - type: StationSpawning

- type: entity
  id: BaseStationRecords
  abstract: true
  components:
    - type: StationRecords

- type: entity
  id: BaseStationArrivals
  abstract: true
  components:
    - type: StationArrivals

- type: entity
  id: BaseStationGateway
  abstract: true
  components:
    - type: GatewayGenerator

- type: entity
  id: BaseStationShuttles
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/SS220/Shuttles/cargo.yml # SS220 shuttle upd
    - type: GridSpawn
      groups:
        trade: !type:GridSpawnGroup
          addComponents:
            - type: ProtectedGrid
            - type: TradeStation
          paths:
            - /Maps/SS220/Shuttles/trading_outpost.yml # SS220 shuttle upd
        mining: !type:GridSpawnGroup
          paths:
          - /Maps/Shuttles/mining.yml # SS220 shuttle upd
        # Spawn last
        ruins: !type:GridSpawnGroup
          hide: false #SS2200 IFF and Name Hide Reveal
          nameGrid: false #SS2200 IFF and Name Hide Reveal
          minCount: 2
          maxCount: 3 # SS2200 Counter Ruins Update
          stationGrid: false
          paths:
          # - /Maps/Ruins/chunked_tcomms.yml # SS220 Removed with Ruins Update (balance Tweak)
          - /Maps/Ruins/biodome_satellite.yml
          - /Maps/Ruins/derelict.yml
          # - /Maps/Ruins/djstation.yml # SS220 Removed with Ruins Update (balance Tweak)
          # - /Maps/Ruins/empty_flagship.yml # SS220 Removed with Ruins Update (balance Tweak)
          - /Maps/Ruins/old_ai_sat.yml
          - /Maps/Ruins/syndicate_dropship.yml
          # - /Maps/Ruins/whiteship_ancient.yml # SS220 Removed with Ruins Update (balance Tweak)
          # - /Maps/Ruins/whiteship_bluespacejumper.yml # SS220 Removed with Ruins Update (balance Tweak)
          # SS220 Ruins Update Map begin
          - /Maps/SS220/Ruins/Arena_SS220.yml
          - /Maps/SS220/Ruins/Broadaxe_SS220.yml
          - /Maps/SS220/Ruins/CargoOutpost_SS220.yml
          - /Maps/SS220/Ruins/Prison_SS220.yml
          - /Maps/SS220/Ruins/WarshuttleWreck_SS220.yml
          # SS220 Ruins Update Map End
        vgroid: !type:DungeonSpawnGroup
          minimumDistance: 300
          maximumDistance: 350
          nameDataset: names_borer
          stationGrid: false
          addComponents:
          - type: Gravity
            enabled: true
            inherent: true
          protos:
          - VGRoid

- type: entity
  id: BaseStationCentcomm
  abstract: true
  components:
    - type: StationCentcomm

- type: entity
  id: BaseStationEvacuation
  abstract: true
  components:
    - type: StationEmergencyShuttle

- type: entity
  id: BaseStationAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: stationAlerts

- type: entity
  id: BaseStationExpeditions
  abstract: true
  components:
    - type: SalvageExpeditionData

- type: entity
  id: BaseStationMagnet
  abstract: true
  components:
    - type: SalvageMagnetData

- type: entity
  id: BaseStationSiliconLawCrewsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Crewsimov

- type: entity
  id: BaseStationNews
  abstract: true
  components:
    - type: StationNews

- type: entity
  id: BaseStationAllEventsEligible
  abstract: true
  components:
    - type: StationEventEligible # For when someone makes this more granular in the future.
