using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.CultYogg;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.CultYogg.UI;

[GenerateTypedNameReferences]
public sealed partial class MiGoErectMenu : FancyWindow
{
    private readonly MiGoErectBoundUserInterface _owner;
    private List<CultYoggBuildingPrototype>? _buildings;

    public MiGoErectMenu(MiGoErectBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _owner = owner;
    }

    protected override Vector2 ArrangeOverride(Vector2 finalSize)
    {
        finalSize = base.ArrangeOverride(finalSize);
        ItemsContainer.MaxGridWidth = ItemsScrollContainer.Width - ItemsContainer.Margin.SumHorizontal;
        return finalSize;
    }

    public void Update(EntityUid uid, MiGoErectBuiState state)
    {
        _buildings = state.Buildings;
        ItemsContainer.DisposeAllChildren();
        foreach (var building in _buildings.OrderBy(x => x.Order))
        {
            var item = new MiGoErectMenuItem();
            ItemsContainer.AddChild(item);
            item.SetOwner(this);
            item.SetItem(building);
        }
    }

    public void BuildingPressed(CultYoggBuildingPrototype building)
    {
        _owner.OnBuildingSelect(building);
    }
}
