using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared.SS220.CultYogg;


namespace Content.Client.SS220.CultYogg.UI;

[GenerateTypedNameReferences]
public sealed partial class MiGoErectMenu : FancyWindow
{
    public MiGoErectMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(EntityUid uid, MiGoErectBuiState state)
    {
        /*
        state.Laws.Sort();
        LawDisplayContainer.Children.Clear();

        foreach (var law in state.Laws)
        {
            var control = new LawDisplay(uid, law, state.RadioChannels);

            LawDisplayContainer.AddChild(control);
        }
        */
    }
}
